use_frameworks!

platform :ios, '9.0'

target 'HanTestWorking_Example' do
  pod 'HanTestWorking', :path => '../'

  target 'HanTestWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
